services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: azerty
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  db_data:
